# Generated by Django 4.2.5 on 2023-09-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynotes',
            options={'verbose_name_plural': 'my_note'},
        ),
        migrations.AlterModelTable(
            name='mynotes',
            table='my_note',
        ),
    ]
